<a href="https://colab.research.google.com/github/Ken79151/-113B-/blob/main/EX03_01_%E5%85%AC%E5%8F%B8%E8%96%AA%E8%B3%87%E6%A6%82%E6%B3%81%E2%85%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

取得 Name 和 Salary 二欄資料

In [48]:

import pandas as pd


data = {
    'ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Helen', 'Ivy', 'Jack'],
    'Age': [25, 30, 35, 40, 22, 29, 38, 27, 33, 31],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose'],
    'Salary': [50000, 60000, 75000, 80000, 45000, 62000, 72000, 58000, 69000, 71000],
    'Department': ['IT', 'HR', 'Finance', 'Marketing', 'IT', 'HR', 'Finance', 'Marketing', 'IT', 'Finance']
}

df = pd.DataFrame(data)

df

    ID     Name  Age          City  Salary Department
0  101    Alice   25      New York   50000         IT
1  102      Bob   30   Los Angeles   60000         HR
2  103  Charlie   35       Chicago   75000    Finance
3  104    David   40       Houston   80000  Marketing
4  105      Eve   22       Phoenix   45000         IT
5  106    Frank   29  Philadelphia   62000         HR
6  107    Grace   38   San Antonio   72000    Finance
7  108    Helen   27     San Diego   58000  Marketing
8  109      Ivy   33        Dallas   69000         IT
9  110     Jack   31      San Jose   71000    Finance

取出索引值 5 到 8 共 4 筆資料

In [5]:
df.loc[5:8]

    ID   Name  Age          City  Salary Department
5  106  Frank   29  Philadelphia   62000         HR
6  107  Grace   38   San Antonio   72000    Finance
7  108  Helen   27     San Diego   58000  Marketing
8  109    Ivy   33        Dallas   69000         IT

取出索引值 5 到 8 共 4 筆資料

In [6]:
df.iloc[5:9]

    ID   Name  Age          City  Salary Department
5  106  Frank   29  Philadelphia   62000         HR
6  107  Grace   38   San Antonio   72000    Finance
7  108  Helen   27     San Diego   58000  Marketing
8  109    Ivy   33        Dallas   69000         IT

In [7]:
avg_age = df['Age'].mean()
avg_salary = df['Salary'].mean()
avg_salary

np.float64(64200.0)

找出年齡和薪水都高於平均值的人員

In [9]:
avg_age = df['Age'].mean()
avg_salary = df['Salary'].mean()

df[(df['Age']>avg_age)&(df['Salary']>avg_salary)]

    ID     Name  Age         City  Salary Department
2  103  Charlie   35      Chicago   75000    Finance
3  104    David   40      Houston   80000  Marketing
6  107    Grace   38  San Antonio   72000    Finance
8  109      Ivy   33       Dallas   69000         IT

請問公司人員的平均薪水、及最高、最低薪水、中位數？

In [11]:
print(df['Salary'].mean(),df['Salary'].max(),df['Salary'].min(),df['Salary'].median())

64200.0 80000 45000 65500.0

公司共有幾個部門

In [12]:
df['Department'].unique()

array(['IT', 'HR', 'Finance', 'Marketing'], dtype=object)

In [13]:
df.groupby('Department')['Salary'].mean()

Department
Finance      72666.666667
HR           61000.000000
IT           54666.666667
Marketing    69000.000000
Name: Salary, dtype: float64

In [14]:
df.groupby('Department')['Salary'].mean().max()

72666.66666666667

那個部門薪水最高？

In [16]:
print(df.groupby('Department')['Salary'].mean().idxmax(),df.groupby('Department')['Salary'].mean().max())

Finance 72666.66666666667

那個部門最年輕？

In [17]:
print(df.groupby('Department')['Age'].mean().idxmin(),df.groupby('Department')['Age'].mean().min())

IT 26.666666666666668

年齡是否與薪資有關？

In [18]:
corr_matrix = df[['Age','Salary']].corr()
corr_matrix

             Age    Salary
Age     1.000000  0.949344
Salary  0.949344  1.000000

In [26]:
df['Company'] = 'TechCorp'
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary,High Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0,No
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0,No
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0,Yes
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0,Yes
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0,No
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0,No
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0,Yes
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0,No
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0,Yes
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0,Yes

In [25]:
df['Annual Salary'] = df['Salary']* 13.5
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary,High Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0,No
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0,No
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0,Yes
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0,Yes
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0,No
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0,No
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0,Yes
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0,No
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0,Yes
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0,Yes

In [24]:
#新增高薪欄位 (薪資高於65000 標記yes 否則no )
df['High Salary'] = df['Salary'].apply(lambda x: 'Yes' if x > 65000 else 'No')
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary,High Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0,No
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0,No
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0,Yes
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0,Yes
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0,No
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0,No
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0,Yes
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0,No
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0,Yes
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0,Yes

In [27]:
df.drop(columns=['High Salary'],inplace=True)
df

#另一種方法
df= df.drop(columns=['High Salary'])

    ID     Name  Age          City  Salary Department   Company  Annual Salary
0  101    Alice   25      New York   50000         IT  TechCorp       675000.0
1  102      Bob   30   Los Angeles   60000         HR  TechCorp       810000.0
2  103  Charlie   35       Chicago   75000    Finance  TechCorp      1012500.0
3  104    David   40       Houston   80000  Marketing  TechCorp      1080000.0
4  105      Eve   22       Phoenix   45000         IT  TechCorp       607500.0
5  106    Frank   29  Philadelphia   62000         HR  TechCorp       837000.0
6  107    Grace   38   San Antonio   72000    Finance  TechCorp       972000.0
7  108    Helen   27     San Diego   58000  Marketing  TechCorp       783000.0
8  109      Ivy   33        Dallas   69000         IT  TechCorp       931500.0
9  110     Jack   31      San Jose   71000    Finance  TechCorp       958500.0

In [30]:
# 使用串列方式新增一筆資料（按照 DataFrame 欄位順序）
df.loc[len(df)] = [111, 'Kevin', 28, 'Austin', 67000, 'IT','TechCorp',360000]
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0
10,111,Kevin,28,Austin,67000,IT,TechCorp,360000.0

In [31]:
new_data = [
    {'ID': 112, 'Name': 'Lily', 'Age': 26, 'City': 'Seattle', 'Salary': 55000, 'Department': 'Marketing'}
]
new_df= pd.DataFrame(new_data)
new_df

    ID  Name  Age     City  Salary Department
0  112  Lily   26  Seattle   55000  Marketing

In [33]:
df = pd.concat([df,new_df],ignore_index=True)
df

,ID,Name,Age,City,Salary,Department,Company,Annual Salary
0,101,Alice,25,New York,50000,IT,TechCorp,675000.0
1,102,Bob,30,Los Angeles,60000,HR,TechCorp,810000.0
2,103,Charlie,35,Chicago,75000,Finance,TechCorp,1012500.0
3,104,David,40,Houston,80000,Marketing,TechCorp,1080000.0
4,105,Eve,22,Phoenix,45000,IT,TechCorp,607500.0
5,106,Frank,29,Philadelphia,62000,HR,TechCorp,837000.0
6,107,Grace,38,San Antonio,72000,Finance,TechCorp,972000.0
7,108,Helen,27,San Diego,58000,Marketing,TechCorp,783000.0
8,109,Ivy,33,Dallas,69000,IT,TechCorp,931500.0
9,110,Jack,31,San Jose,71000,Finance,TechCorp,958500.0
10,111,Kevin,28,Austin,67000,IT,TechCorp,360000.0
11,112,Lily,26,Seattle,55000,Marketing,NaN,NaN
12,112,Lily,26,Seattle,55000,Marketing,NaN,NaN

In [46]:
# 刪除索引為 2 的資料
df= df.drop(index= 2, inplace=True)
df

In [49]:
condition = df['Salary'] < 75000
df = df[condition]
df

    ID   Name  Age          City  Salary Department
0  101  Alice   25      New York   50000         IT
1  102    Bob   30   Los Angeles   60000         HR
4  105    Eve   22       Phoenix   45000         IT
5  106  Frank   29  Philadelphia   62000         HR
6  107  Grace   38   San Antonio   72000    Finance
7  108  Helen   27     San Diego   58000  Marketing
8  109    Ivy   33        Dallas   69000         IT
9  110   Jack   31      San Jose   71000    Finance

In [50]:
# 計算每一欄有多少個 NaN
df.isnull().sum()

ID            0
Name          0
Age           0
City          0
Salary        0
Department    0
dtype: int64

In [53]:
# 找出具有空值的列
df[['ID','Name']].isnull().any(axis=1)

0    False
1    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [54]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [ID, Name, Age, City, Salary, Department]
Index: []

In [55]:
df.loc[4,'Salary'] = pd.NA
df

    ID   Name  Age          City   Salary Department
0  101  Alice   25      New York  50000.0         IT
1  102    Bob   30   Los Angeles  60000.0         HR
4  105    Eve   22       Phoenix      NaN         IT
5  106  Frank   29  Philadelphia  62000.0         HR
6  107  Grace   38   San Antonio  72000.0    Finance
7  108  Helen   27     San Diego  58000.0  Marketing
8  109    Ivy   33        Dallas  69000.0         IT
9  110   Jack   31      San Jose  71000.0    Finance

In [57]:
# 用平均數填充 Salary 欄位
df['Salary'] = df['Salary'].fillna(df['Salary'].mean())
df

<ipython-input-57-29c5ab0df49b>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Salary'] = df['Salary'].fillna(df['Salary'].mean())

    ID   Name  Age          City        Salary Department
0  101  Alice   25      New York  50000.000000         IT
1  102    Bob   30   Los Angeles  60000.000000         HR
4  105    Eve   22       Phoenix  63142.857143         IT
5  106  Frank   29  Philadelphia  62000.000000         HR
6  107  Grace   38   San Antonio  72000.000000    Finance
7  108  Helen   27     San Diego  58000.000000  Marketing
8  109    Ivy   33        Dallas  69000.000000         IT
9  110   Jack   31      San Jose  71000.000000    Finance

In [58]:
# 替換 'IT' 部門為 'Information Technology'
df['Department'] = df['Department'].replace('IT', 'Information Technology')
df

<ipython-input-58-1fc065d9182a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Department'] = df['Department'].replace('IT', 'Information Technology')

    ID   Name  Age          City        Salary              Department
0  101  Alice   25      New York  50000.000000  Information Technology
1  102    Bob   30   Los Angeles  60000.000000                      HR
4  105    Eve   22       Phoenix  63142.857143  Information Technology
5  106  Frank   29  Philadelphia  62000.000000                      HR
6  107  Grace   38   San Antonio  72000.000000                 Finance
7  108  Helen   27     San Diego  58000.000000               Marketing
8  109    Ivy   33        Dallas  69000.000000  Information Technology
9  110   Jack   31      San Jose  71000.000000                 Finance

In [59]:
# 如果 City 是 'New York'，則改為 'NYC'
df['City'] = df['City'].apply(lambda x: 'NYC' if x == 'New York' else x)

<ipython-input-59-d2df4ede748a>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['City'] = df['City'].apply(lambda x: 'NYC' if x == 'New York' else x)